/**
 * Statement metadata per account — what a bank statement says ABOUT its transactions: the period it
 * covers, its opening and closing balance and, for CAMT, its running number.
 *
 * The transaction store keeps only the bookings, so before this file a missing CAMT file was
 * invisible: the EÜR simply summed fewer transactions. The balances and numbers are what makes the
 * gap provable (opening + Σ bookings = closing; closing of one statement = opening of the next).
 *
 * One `statements.json` next to the NDJSON files, keyed by account. It lives in the gitignored store
 * directory and is regenerated by re-importing the statements, like the transactions themselves.
 */

import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { getStoreDir, activeImportBatch } from './store.ts';

const STATEMENTS_FILE = 'statements.json';

/** One bank statement's metadata. Dates are YYYY-MM-DD; amounts signed EUR. */
export interface StatementMeta {
  /** First and last day the statement covers. */
  from: string;
  to: string;
  /** Opening / closing balance; absent when the file carried none. */
  opening?: number;
  closing?: number;
  /** Running statement number (CAMT `ElctrncSeqNb` / `LglSeqNb`) when the file carries one. */
  seq?: number;
  /** Σ and count of the statement's own entries. */
  sum: number;
  count: number;
  /** Where the metadata came from. */
  source: 'camt' | 'fints' | 'demo';
  /** The import batch that brought it in (see withImportBatch). */
  importBatch?: string;
}

function statementKey(s: StatementMeta): string {
  return `${s.from}|${s.to}|${s.seq ?? ''}`;
}

/** All stored statement metadata, keyed by account key (each list oldest → newest). */
export function readStatements(): Record<string, StatementMeta[]> {
  const p = join(getStoreDir(), STATEMENTS_FILE);
  if (!existsSync(p)) return {};
  try {
    return JSON.parse(readFileSync(p, 'utf8')) as Record<string, StatementMeta[]>;
  } catch {
    return {};
  }
}

/** The stored statements of one account, oldest → newest. */
export function loadStatements(accountKey: string): StatementMeta[] {
  return readStatements()[accountKey] ?? [];
}

function writeStatements(all: Record<string, StatementMeta[]>): void {
  const dir = getStoreDir();
  if (!existsSync(dir)) mkdirSync(dir, { recursive: true });
  const sorted: Record<string, StatementMeta[]> = {};
  for (const key of Object.keys(all).sort()) {
    if (all[key].length) sorted[key] = all[key];
  }
  writeFileSync(join(dir, STATEMENTS_FILE), `${JSON.stringify(sorted, null, 2)}\n`);
}

/**
 * Merge statement metadata into an account (upsert by period + number). Re-importing the same file
 * replaces its entries instead of doubling them; a statement already known keeps its import batch.
 */
export function upsertStatements(accountKey: string, incoming: StatementMeta[]): { added: number; total: number } {
  if (incoming.length === 0) return { added: 0, total: loadStatements(accountKey).length };
  const all = readStatements();
  const map = new Map((all[accountKey] ?? []).map((s) => [statementKey(s), s]));
  let added = 0;
  const batch = activeImportBatch();
  for (const s of incoming) {
    const k = statementKey(s);
    const existing = map.get(k);
    if (!existing) added++;
    const importBatch = existing ? existing.importBatch : (batch ?? undefined);
    map.set(k, importBatch ? { ...s, importBatch } : s);
  }
  all[accountKey] = [...map.values()].sort((a, b) =>
    a.from !== b.from ? (a.from < b.from ? -1 : 1) : (a.seq ?? 0) - (b.seq ?? 0),
  );
  writeStatements(all);
  return { added, total: all[accountKey].length };
}

/** Drop the statements an import batch added — the counterpart of {@link undoImport}. */
export function undoImportStatements(batchId: string): number {
  const all = readStatements();
  let removed = 0;
  for (const key of Object.keys(all)) {
    const keep = all[key].filter((s) => s.importBatch !== batchId);
    removed += all[key].length - keep.length;
    all[key] = keep;
  }
  if (removed) writeStatements(all);
  return removed;
}
